### ISSUE TITLE
Extensibility - please allow a way to run this report from within PHP

### ISSUE THREAD

**Issue by fredden** [sansecio/composer-integrity-plugin#11]
Following @danslo's presentation at [Mage Titans UK 2023](https://uk.magetitans.com/), @pykettk and I discussed creating a Magento module to wrap this plug-in, and surface the results in the admin portal and trigger alerts, etc. Kiel has done this in https://github.com/element119/module-sansec-composer-integrity-checker :+1:

However, it doesn't seem possible to access the report from this plug-in without invoking Composer. Please can you create a public PHP interface so that the report can be retrieved from within PHP? This will help with extensibility.

**Comment by danslo** [comment]
I'm unsure if this is possible, as we currently rely on composer object to get installed packages as well as locked versions.

It should be possible to manually read composer.lock of course, but I'm not sure I want to implement that.

I could provide a `PackageResolverStrategy` interface rather than relying on `Composer\Composer`, so at least anyone can do what they want. Would that work for you?

**Comment by danslo** [comment]
This should be fixed with https://github.com/sansecio/composer-integrity-plugin/pull/14. I've posted an example in that PR.

**Comment by pykettk** [comment]
Thanks both for the discussion! I'll check that PR out later this evening, @danslo - thanks for the efforts 🙂
